export const paints_url = "/.netlify/functions/all-items";

export const paints = [
  {
    id: 1,
    title: "פריחה בלילה",
    category: "שמן",
    price: 720,
    img: "./images/item-11.jpeg",
    dimention: "30 * 55",
    materials: "שמן",
  },
  {
    id: 2,
    title: "אשכול ענבים",
    category: "אקריל",
    price: 13.99,
    img: "./images/item-12.jpeg",
    dimention: "30 * 55",
    materials: "שמן",
  },
  {
    id: 3,
    title: "בית ביוון",
    category: "מים",
    price: 6.99,
    img: "./images/item-12.jpeg",
    dimention: "30 * 55",
    materials: "שמן",
  },
  {
    id: 4,
    title: "country delight",
    category: "מים",
    price: 20.99,
    img: "./images/item-12.jpeg",
    dimention: "30 * 55",
    materials: "שמן",
  },
  {
    id: 5,
    title: "egg attack",
    category: "רישום",
    price: 22.99,
    img: "./images/item-12.jpeg",
    dimention: "30 * 55",
    materials: "שמן",
  },
  {
    id: 6,
    title: "oreo dream",
    category: "פחם",
    price: 18.99,
    img: "./images/item-11.jpeg",
    dimention: "30 * 55",
    materials: "שמן",
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "פחם",
    price: 8.99,
    img: "./images/item-11.jpeg",
    dimention: "30 * 55",
    materials: "שמן",
  },
  {
    id: 8,
    title: "american classic",
    category: "שמן",
    price: 12.99,
    img: "./images/item-11.jpeg",
    dimention: "30 * 55",
    materials: "שמן",
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "מים",
    price: 16.99,
    img: "./images/item-12.jpeg",
    dimention: "30 * 55",
    materials: "שמן",
  },
];
export const links = [
  {
    id: 3,
    url: "/",
    text: "בית",
  },
  {
    id: 2,
    url: "/collection",
    text: "אוסף",
  },

  {
    id: 1,
    url: "/contact",
    text: "צרו קשר",
  },
];
